### ISSUE TITLE
Is there a way to set a proxy for the actions set in ``feature``?

### ISSUE THREAD

**Issue by ksaito1125** [devcontainers/templates#32]
When adding a development container, the following devcontainer.json was added.

```
{
	"name": "Python 3",
	"image": "mcr.microsoft.com/devcontainers/python:3.10-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"version": "lts"
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "pip3 install --user -r requirements.txt",

	// Set `remoteUser` to `root` to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}
```

When I start the development container under the proxy environment, I get the following error.

```
[2022-11-04T02:46:16.377Z]  ---> Running in cb3df42a48be
[2022-11-04T02:46:16.724Z] ===========================================================================
Feature       : Node.js (via nvm) and yarn
Description   : Installs Node.js, nvm, yarn, and needed dependencies.
Id            : ghcr.io/devcontainers/features/node
Version       : 1.1.1
Documentation : https://github.com/devcontainers/features/tree/main/src/node
Options       :
    VERSION="lts"
    NODEGYPDEPENDENCIES="true"
    NVMINSTALLPATH="/usr/local/share/nvm"
    NVMVERSION="0.39.2"
===========================================================================
[2022-11-04T02:46:16.822Z] Yarn already installed.
[2022-11-04T02:46:16.856Z] NVM already installed.
[2022-11-04T02:49:52.504Z] Version '' (with LTS filter) not found - try `nvm ls-remote --lts` to browse available versions.
[2022-11-04T02:49:52.507Z] ERROR: Feature "Node.js (via nvm) and yarn" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
[2022-11-04T02:49:52.684Z] The command '/bin/sh -c cd /tmp/build-features/node_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh' returned a non-zero code: 3
[2022-11-04T02:49:52.689Z] Stop (216570 ms): Run: docker build --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/python:3.10-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ms-identity-javascript-react-spa-1693c68eb136e712db187f2bdf7e772d-features -f /tmp/devcontainercli-ubuntu/container-features/0.23.2-1667529973984/Dockerfile.extended /tmp/devcontainercli-ubuntu/empty-folder
[2022-11-04T02:49:52.687Z] Error: Command failed: docker build --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/python:3.10-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ms-identity-javascript-react-spa-1693c68eb136e712db187f2bdf7e772d-features -f /tmp/devcontainercli-ubuntu/container-features/0.23.2-1667529973984/Dockerfile.extended /tmp/devcontainercli-ubuntu/empty-folder
[2022-11-04T02:49:52.687Z]     at loe (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:1339)
[2022-11-04T02:49:52.688Z]     at eT (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:1275)
[2022-11-04T02:49:52.688Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-04T02:49:52.688Z]     at async voe (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:2049)
[2022-11-04T02:49:52.689Z]     at async Xf (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:3212)
[2022-11-04T02:49:52.689Z]     at async Jae (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:15058)
[2022-11-04T02:49:52.689Z]     at async Wae (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:14812)
[2022-11-04T02:49:52.692Z] Stop (219084 ms): Run in Host: /home/ubuntu/.vscode-remote-containers/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa --log-level debug --log-format json --config /home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-04T02:49:52.692Z] Exit code 1
[2022-11-04T02:49:52.704Z] Command failed: /home/ubuntu/.vscode-remote-containers/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa --log-level debug --log-format json --config /home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-04T02:49:52.704Z] Exit code 1
```

Looking at the log, I noticed that ``docker build`` did not have a proxy set with ``--build-arg``.

```
[2022-11-04T02:46:14.041Z] * Processing feature: ghcr.io/devcontainers/features/node:1
[2022-11-04T02:46:14.634Z] * Fetching feature: node_1_oci
[2022-11-04T02:46:15.277Z] Start: Run: docker build -t dev_container_feature_content_temp -f /tmp/devcontainercli-ubuntu/container-features/0.23.2-1667529973984/Dockerfile.buildContent /tmp/devcontainercli-ubuntu/container-features/0.23.2-1667529973984
[2022-11-04T02:46:15.382Z] Sending build context to Docker daemon  328.2kB
```

Is there a way to set a proxy for the actions set in ``feature``?

**Comment by ksaito1125** [comment]
After adding ``Dockerfile`` and modifying ``devcontainer.json`` as shown below, the error disappeared.

```Dockerfile
FROM mcr.microsoft.com/devcontainers/python:3.10-bullseye
```

```
{
	"name": "Python 3",
	"build": {
		"dockerfile": "Dockerfile",
		"context": "..",
		"args": {
			// Update 'VARIANT' to pick a Python version: 3, 3.10, 3.9, 3.8, 3.7, 3.6
			// Append -bullseye or -buster to pin to an OS version.
			// Use -bullseye variants on local on arm64/Apple Silicon.
			"http_proxy": "${localEnv:http_proxy}",
			"https_proxy": "${localEnv:http_proxy}",
			"no_proxy": "${localEnv:no_proxy}"
		}
	},
	// "image": "mcr.microsoft.com/devcontainers/python:3.10-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"version": "lts"
		}
	},
	"containerEnv": {
		"http_proxy": "${localEnv:http_proxy}",
		"https_proxy": "${localEnv:http_proxy}",
		"no_proxy": "${localEnv:no_proxy}"
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "pip3 install --user -r requirements.txt",

	// Set `remoteUser` to `root` to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}
```

**Comment by ksaito1125** [comment]
Looking at the log, proxy is set with ``--build-arg`` in ``docker build``.
Is it possible to set proxy with ``build-arg`` even if only image is specified in devcontainer.json?

```
[18451 ms] Start: Run: docker build -f /tmp/devcontainercli-ubuntu/container-features/0.23.2-1667539011852/Dockerfile-with-features -t vsc-ms-identity-javascript-react-spa-1693c68eb136e712db187f2bdf7e772d --target dev_containers_target_stage --build-arg http_proxy=http://proxy.xxx.co.jp:8080 --build-arg https_proxy=http://proxy.xxx.co.jp:8080 --build-arg no_proxy=localhost,127.0.0.1 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/ubuntu/ghq/github.com/ksaito1125/ms-identity-javascript-react-spa
```

**Comment by ksaito1125** [comment]
Thank you for replay.

I am using the same version.

* ms-vscode-remote.remote-containers v0.262.3

I tried again with a new project and got the same error.

The environment I'm working in connects to the internet through a proxy.
I'm guessing that the Node.js error message in the first log is due to a failure to access the internet, which is required when the feature sets node in the started container.

Because after specifying none for the Node.js version in Add Dev Container Configuration Files, the dev container worked fine.

**Comment by ksaito1125** [comment]
Problem solved.

I set the proxy in $HOME/.docker/config.json according to the document below.

https://matsuand.github.io/docs.docker.jp.onthefly/network/proxy/#configure-the-docker-client

The ``.devcontainer`` settings were left at their default settings, and the development container started.
The proxy was also set correctly in the environment variables of the started container.

```
vscode ➜ /workspaces/default $ env | grep -i proxy
no_proxy=localhost,127.0.0.1
https_proxy=http://proxy.xxx.co.jp:8080
NO_PROXY=localhost,127.0.0.1
HTTPS_PROXY=http://proxy.xxx.co.jp:8080
HTTP_PROXY=http://proxy.xxx.co.jp:8080
http_proxy=http://proxy.xxx.co.jp:8080
```

I think it's the best setting I've tried so far.
